### PR TITLE
Set PHP error_reporting to E_ALL

### PR DESCRIPTION
**Pull request by john-n-smith**
@h-bragg, are you down with this change?
Would it be a better idea add a `php.ini` file to the repo and mount it?

### CODE REVIEW

**Comment by h-bragg** [comment]
I would probably say this is the responsibility of each repository to define their php configuration. Willing to change my mind though.

**Comment by john-n-smith** [comment]
@h-bragg, it seems good practice to me to write code that does not create any errors in PHP. Maybe this is something we could add to `graze/standards`, before enforcing here.

**Comment by h-bragg** [comment]
Yeah, probably.

Maybe we could do it differently:

1. Include the base php.ini file in this repository
2. Include a php.ini file to be added to the `/etc/php/conf.d/` directory with just this setting in it. Then this file can be modified by each repository and its there...

I like the second option (i think stats does this now w/ dev and production)

**Comment by john-n-smith** [comment]
That was my suggestion in the PR description 😄 
I'll do that and suggest it as a standard.

**Pull request closed without merging**
